name: Tests
on:
  pull_request:
    branches:
      - master
jobs:
  test-go:
    name: Go
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cover
        run: go get golang.org/x/tools/cmd/cover
      - name: Tests
        run: go test ./... -race -v -coverprofile=coverage.out && ./cover-check.sh coverage.out 8.4
